---

- name: Instalar paquetes samba
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ paquetes }}"


- name: Iniciar servicio samba
  ansible.builtin.service:
    name: smbd
    state: started
    enabled: true


- name: Crear carpeta
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: '0777'
    state: directory
  with_items: "{{ config }}"

- name: Configuracion fichero samba
  ansible.builtin.template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: '0775'


- name: Reiniciar servicio samba
  ansible.builtin.service:
    name: smbd
    state: restarted
  changed_when: false

...
