---

- name: Añadir repo centos8
  ansible.builtin.yum_repository:
    name: centos8
    baseurl: http://mirror.centos.org/centos/8-stream/BaseOS/x86_64/os/
    description: repositorio centos8


- name: Instalar paquetes samba
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
    update_cache: true
    disable_gpg_check: true
  with_items: "{{ paquetes }}"


- name: Iniciar servicio samba
  ansible.builtin.service:
    name: smb
    state: started
    enabled: true


- name: Crear carpeta
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: '0777'
    state: directory
  with_items: "{{ config }}"


- name: Configuracion fichero samba
  ansible.builtin.template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: '0775'


- name: Reiniciar servicio samba
  ansible.builtin.service:
    name: smb
    state: restarted
  changed_when: false

...