---

#repos centos
repos:
  - {
    nombre: baseos,
    url: http://mirror.centos.org/centos/8-stream/BaseOS/x86_64/os/,
    descripcion: repositorio centos baseos
  }


# paquetes samba
paquetes_debian:
  - samba
  - samba-common
  - samba-client
  - python3-pexpect
  - whois

paquetes_redhat:
  - samba
  - samba-common
  - samba-client
  - python3-pip
  - python3
  - openssl


#configuracion smb.conf de las diferentes carpetas
config: 
  - {
    path: /media/compartir_samba,
    nombre_carpeta: carpeta_samba,
    comentario: Carpeta compartida en contenedor docker,
    browsable: yes,
    guest: yes,
    read: no
  }

  - {
    path: /media/compartir_samba2,
    nombre_carpeta: carpeta_samba2,
    comentario: Carpeta compartida en contenedor docker,
    browsable: yes,
    guest: yes,
    read: no
  }


# usuario para smb
usuarios:
  - {
    usuario: sergio,
    contraseña: 123456
  }
  
  - {
    usuario: pepe,
    contraseña: 123456
  }


# grupo para smb
grupo: samba_group

...
