---

- name: Instalar paquetes samba
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ paquetes_debian }}"


- name: Iniciar servicio samba
  ansible.builtin.service:
    name: smbd
    state: started
    enabled: true


- name: Cifrar contraseña
  ansible.builtin.command:
    cmd: mkpasswd {{ item.contraseña }}
  register: hash
  changed_when: false
  with_items: "{{ usuarios }}"


- name: Crear grupo
  ansible.builtin.group:
    name: "{{ grupo }}"
    state: present


- name: Crear usuario
  ansible.builtin.user:
    name: "{{ item.item.usuario }}"
    password: "{{ item.stdout }}"
    groups: "{{ grupo }}"
    state: present
  changed_when: false
  with_items: "{{ hash.results }}"


- name: Añadir usuario a smb
  ansible.builtin.expect:
    command: smbpasswd -a {{ item.usuario }}
    responses:
      New SMB password: "{{ item.contraseña }}"
      Retype new SMB password: "{{ item.contraseña }}"
  changed_when: false
  with_items: "{{ usuarios }}"


- name: Crear carpeta
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: '0777'
    state: directory
  with_items: "{{ config }}"


- name: Configuracion fichero samba
  ansible.builtin.template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: '0775'


- name: Reiniciar servicio samba
  ansible.builtin.service:
    name: smbd
    state: restarted
  changed_when: false 

...
