---

- name: Instalar paquetes samba
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ paquetes_debian }}"


- name: Iniciar servicio samba
  ansible.builtin.service:
    name: smbd
    state: started
    enabled: true


- name: Cifrar contraseña
  ansible.builtin.command:
    cmd: mkpasswd {{ contraseña }}
  register: hash
  changed_when: false


- name: Crear grupo
  ansible.builtin.group:
    name: "{{ grupo }}"
    state: present


- name: Crear usuario
  ansible.builtin.user:
    name: "{{ usuario }}"
    password: "{{ hash.stdout }}"
    groups: "{{ grupo }}"
    state: present
  changed_when: false


- name: Añadir usuario a smb
  ansible.builtin.expect:
    command: smbpasswd -a {{ usuario }}
    responses:
      New SMB password: "{{ contraseña }}"
      Retype new SMB password: "{{ contraseña }}"
  changed_when: false


- name: Crear carpeta
  ansible.builtin.file:
    path: "{{ path }}"
    owner: root
    group: "{{ grupo }}"
    mode: '0777'
    state: directory


- name: Configuracion fichero samba
  ansible.builtin.blockinfile:
    path: /etc/samba/smb.conf
    block: |
      [{{ nombre_carpeta }}]
        comment = {{ comentario }}
        path = {{ path }}
        valid users = @{{ grupo }}
        browsable = {{ browsable }}
        guest ok = {{ guest }}
        read only = {{ read }}


- name: Reiniciar servicio samba
  ansible.builtin.service:
    name: smbd
    state: restarted
  changed_when: false 

...
