---

- name: Incluir samba Debian
  ansible.builtin.include_tasks: debian.yml
  when: ansible_distribution == "Debian"


- name: Incluir samba Redhat
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_distribution == "RedHat"

...
