---

- name: Añadir repo centos8
  ansible.builtin.yum_repository:
    name: centos8
    baseurl: http://mirror.centos.org/centos/8-stream/BaseOS/x86_64/os/
    description: repositorio centos8


- name: Instalar paquetes samba
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
    update_cache: true
    disable_gpg_check: true
  with_items: "{{ paquetes_redhat }}"


- name: Instalar pexpect
  ansible.builtin.pip:
    name: pexpect
    state: present


- name: Iniciar servicio samba
  ansible.builtin.service:
    name: smb
    state: started
    enabled: true


- name: Copiar fichero python para hash
  ansible.builtin.template:
    dest: /tmp/hash.py
    src: hash.py
    owner: root
    group: root
    mode: '0755'


- name: Crear hash de contraseña
  ansible.builtin.command:
    cmd: python3 hash.py
    chdir: /tmp
  register: hash
  changed_when: false


- name: Crear grupo
  ansible.builtin.group:
    name: "{{ grupo }}"
    state: present


- name: Crear usuario
  ansible.builtin.user:
    name: "{{ usuario }}"
    password: "{{ hash.stdout }}"
    groups: "{{ grupo }}"
    state: present
  changed_when: false


- name: Añadir usuario a smb
  ansible.builtin.expect:
    command: smbpasswd -a {{ usuario }}
    responses:
      New SMB password: "{{ contraseña }}"
      Retype new SMB password: "{{ contraseña }}"
  changed_when: false


- name: Crear carpeta
  ansible.builtin.file:
    path: "{{ path }}"
    owner: root
    group: "{{ grupo }}"
    mode: '0777'
    state: directory


- name: Configuracion fichero samba
  ansible.builtin.blockinfile:
    path: /etc/samba/smb.conf
    block: |
      [{{ nombre_carpeta }}]
        comment = {{ comentario }}
        path = {{ path }}
        valid users = @{{ grupo }}
        browsable = {{ browsable }}
        guest ok = {{ guest }}
        read only = {{ read }}

        
- name: Reiniciar servicio samba
  ansible.builtin.service:
    name: smb
    state: restarted
  changed_when: false 

- name: Eliminar fichero hash.py
  ansible.builtin.file:
    path: /tmp/hash.py
    state: absent

...
