---

- name: Añadir repositorios
  ansible.builtin.yum_repository:
    name: "{{ item.nombre }}"
    baseurl: "{{ item.url }}"
    description: "{{ item.url }}"
  with_items: "{{ repos }}"


- name: Instalar paquetes samba
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
    update_cache: true
    disable_gpg_check: true
  with_items: "{{ paquetes_redhat }}"


- name: Instalar pexpect
  ansible.builtin.pip:
    name: pexpect
    state: present


- name: Iniciar servicio samba
  ansible.builtin.service:
    name: smb
    state: started
    enabled: true


- name: Cifrar contraseña
  ansible.builtin.command:
    cmd: openssl passwd -6 {{ item.contraseña }}
  register: hash
  changed_when: false
  with_items: "{{ usuarios }}"


- name: Crear grupo
  ansible.builtin.group:
    name: "{{ grupo }}"
    state: present


- name: Crear usuario
  ansible.builtin.user:
    name: "{{ item.item.usuario }}"
    password: "{{ item.stdout }}"
    groups: "{{ grupo }}"
    state: present
  changed_when: false
  with_items: "{{ hash.results }}"


- name: Añadir usuario a smb
  ansible.builtin.expect:
    command: smbpasswd -a {{ item.usuario }}
    responses:
      New SMB password: "{{ item.contraseña }}"
      Retype new SMB password: "{{ item.contraseña }}"
  changed_when: false
  with_items: "{{ usuarios }}"


- name: Crear carpeta
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: '0777'
    state: directory
  with_items: "{{ config }}"


- name: Configuracion fichero samba
  ansible.builtin.template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: '0775'

        
- name: Reiniciar servicio samba
  ansible.builtin.service:
    name: smb
    state: restarted
  changed_when: false 

- name: Eliminar fichero hash.py
  ansible.builtin.file:
    path: /tmp/hash.py
    state: absent

...
