---

#paquetes samba
paquetes:
  - samba
  - samba-common


# path de carpeta a compartir
path: /media/compartir_samba

#configuracion smb.conf
nombre_carpeta: carpeta_samba
comentario: Carpeta compartida en contenedor docker
browsable: yes
guest: yes
read: no

...