---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: Debian
    image: docker.io/debian:latest
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
