---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  vars_files:
    - main.yml
  tasks:

  - name: Conexion a carpeta compartida
    shell: smbclient //localhost/{{ item.nombre_carpeta }} -U {{ usuarios[0].usuario }} {{ usuarios[0].contraseña }}
    register: conexion
    with_items: "{{ config }}"


  - name: Comprobar conexion
    ansible.builtin.assert:
      that: 'item.rc == 0 and "Try \"help\" to get a list of possible commands." in item.stdout'
      success_msg: "Conexion a {{ item.item.nombre_carpeta }} realizada correctamente"
    with_items: "{{ conexion.results }}"      